dist: bionic

sudo: false

language: php

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer/cache

branches:
  only:
    - main

matrix:
  include:
    - php: 7.3

before_install:
  - |
    export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi

install:
  - composer install -n
  - chmod 755 tests/output

script:
  - |
    ./vendor/bin/phpcs --config-set installed_paths ../../alley,../../wp-coding-standards/wpcs,../../sirbrillig/phpcs-variable-analysis,../../automattic/vipwpcs
    ./vendor/bin/phpcs --standard=./phpcs.xml .
  - composer run phpunit
